// <auto-generated />
using Demo_LINQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo_LINQ.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210715004911_M0_InitialMigration")]
    partial class M0_InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo_LINQ.Models.Department", b =>
                {
                    b.Property<string>("NumDepartment")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Num_Department");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_Department");

                    b.HasKey("NumDepartment")
                        .HasName("PK__Departme__2F3606BCA41F1BA0");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Employe", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdSup")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_Sup");

                    b.Property<string>("NameEmploye")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_Employe");

                    b.Property<string>("NumDepartment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Num_Department");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Salaire")
                        .HasColumnType("money");

                    b.HasKey("Matricule")
                        .HasName("PK__Employe__0FB9FB42F29433F5");

                    b.HasIndex("IdSup");

                    b.HasIndex("NumDepartment");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Fournisseur", b =>
                {
                    b.Property<string>("NumFourniture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Num_Fourniture");

                    b.Property<string>("NameFournisseur")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_Fournisseur");

                    b.Property<string>("Ville")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("NumFourniture")
                        .HasName("PK__Fourniss__C10ED305FC51716E");

                    b.ToTable("Fournisseur");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Fourniture", b =>
                {
                    b.Property<string>("CodeProduit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code_Produit");

                    b.Property<string>("NumFourniture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Num_Fourniture");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasIndex("CodeProduit");

                    b.HasIndex("NumFourniture");

                    b.ToTable("Fourniture");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Participer", b =>
                {
                    b.Property<string>("Matricule")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodeProjet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code_Projet");

                    b.HasKey("Matricule", "CodeProjet")
                        .HasName("PK__Particip__D4B452D79391D420");

                    b.HasIndex("CodeProjet");

                    b.ToTable("Participer");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Produit", b =>
                {
                    b.Property<string>("CodeProduit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code_Produit");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CodeProduit")
                        .HasName("PK__Produit__1706ED70D67EE8A2");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Projet", b =>
                {
                    b.Property<string>("CodeProjet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code_Projet");

                    b.Property<string>("NameProjet")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_Projet");

                    b.HasKey("CodeProjet")
                        .HasName("PK__Projet__B0DA995C0ACED830");

                    b.ToTable("Projet");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Employe", b =>
                {
                    b.HasOne("Demo_LINQ.Models.Employe", "IdSupNavigation")
                        .WithMany("InverseIdSupNavigation")
                        .HasForeignKey("IdSup")
                        .HasConstraintName("FK__Employe__ID_Sup__38996AB5");

                    b.HasOne("Demo_LINQ.Models.Department", "NumDepartmentNavigation")
                        .WithMany("Employes")
                        .HasForeignKey("NumDepartment")
                        .HasConstraintName("FK__Employe__Num_Dep__398D8EEE")
                        .IsRequired();

                    b.Navigation("IdSupNavigation");

                    b.Navigation("NumDepartmentNavigation");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Fourniture", b =>
                {
                    b.HasOne("Demo_LINQ.Models.Produit", "CodeProduitNavigation")
                        .WithMany()
                        .HasForeignKey("CodeProduit")
                        .HasConstraintName("FK__Fournitur__Code___45F365D3");

                    b.HasOne("Demo_LINQ.Models.Fournisseur", "NumFournitureNavigation")
                        .WithMany()
                        .HasForeignKey("NumFourniture")
                        .HasConstraintName("FK__Fournitur__Num_F__44FF419A")
                        .IsRequired();

                    b.Navigation("CodeProduitNavigation");

                    b.Navigation("NumFournitureNavigation");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Participer", b =>
                {
                    b.HasOne("Demo_LINQ.Models.Projet", "CodeProjetNavigation")
                        .WithMany("Participers")
                        .HasForeignKey("CodeProjet")
                        .HasConstraintName("FK__Participe__Code___3F466844")
                        .IsRequired();

                    b.HasOne("Demo_LINQ.Models.Employe", "MatriculeNavigation")
                        .WithMany("Participers")
                        .HasForeignKey("Matricule")
                        .HasConstraintName("FK__Participe__Matri__3E52440B")
                        .IsRequired();

                    b.Navigation("CodeProjetNavigation");

                    b.Navigation("MatriculeNavigation");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Department", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Employe", b =>
                {
                    b.Navigation("InverseIdSupNavigation");

                    b.Navigation("Participers");
                });

            modelBuilder.Entity("Demo_LINQ.Models.Projet", b =>
                {
                    b.Navigation("Participers");
                });
#pragma warning restore 612, 618
        }
    }
}
